### ISSUE TITLE
Only cx11 works correctly

### ISSUE THREAD

**Issue by petrkozorezov** [lukebfox/nixops-hetznercloud#3]
Others instance types contain different network interface names.
E.g. `cx21`
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 96:00:00:8e:44:d2 brd ff:ff:ff:ff:ff:ff
    inet 95.217.23.198/32 brd 95.217.23.198 scope global dynamic enp1s0
       valid_lft 86060sec preferred_lft 75260sec
    inet6 fe80::9400:ff:fe8e:44d2/64 scope link
       valid_lft forever preferred_lft forever
3: enp7s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc fq_codel state UP group default qlen 1000
    link/ether 86:00:00:8e:46:aa brd ff:ff:ff:ff:ff:ff
    inet 192.168.3.1/32 brd 192.168.3.1 scope global dynamic enp7s0
       valid_lft 86055sec preferred_lft 75255sec
    inet6 fe80::8400:ff:fe8e:46aa/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by lukebfox** [comment]
So it looks like there are two link naming schemes for Hetzner Cloud at the moment:
* Legacy (cx):  ens3 for wired; ens10, ens11, and ens12 for server networks.
* New (cpx):  enp1s0 for wired; enp7s0, enp8s0, and enp9s0 for server networks.

Currently nixops_hetznercloud only derives server network link names from `server_type`,
https://github.com/lukebfox/nixops-hetznercloud/blob/34075a96ef75fb33eec46844e7587fe4cd141938/nixops_hetznercloud/backends/hetznercloud.py#L207-L211

Additionally deriving the wired link name from `server_type` isn't enough because whichever scheme you get when you provision the server initially is the one you keep i.e. if you provision a `cx21` and upgrade it to a `cpx21` it will keep `cx` style link names, or if you provision a `cpx21` and upgrade it to a `cx31` it will keep `cpx` style link names. Because we can't derive names from `server_type` we'll track which scheme we started with in the state and derive the names from that.
